[package]
name = "ap_federation"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
chrono = { version = "0.4.24", features = ["clock"], default-features = false }
serde = { version = "1.0.159", features = ["derive"] }
async-trait = "0.1.68"
url = { version = "2.3.1", features = ["serde"] }
serde_json = { version = "1.0.95", features = ["preserve_order"] }
anyhow = "1.0.70"
reqwest = { version = "0.11.16", features = ["json", "stream"] }
reqwest-middleware = "0.2.1"
tracing = "0.1.37"
base64 = "0.21.0"
openssl = "0.10.48"
once_cell = "1.17.1"
http = "0.2.9"
sha2 = "0.10.6"
background-jobs = "0.13.0"
thiserror = "1.0.40"
derive_builder = "0.12.0"
itertools = "0.10.5"
dyn-clone = "1.0.11"
enum_delegate = "0.2.0"
httpdate = "1.0.2"
http-signature-normalization-reqwest = { version = "0.8.0", default-features = false, features = ["sha-2", "middleware"] }
http-signature-normalization = "0.7.0"
bytes = "1.4.0"
futures-core = { version = "0.3.27", default-features = false }
pin-project-lite = "0.2.9"
activitystreams-kinds = "0.3.0"
regex = { version = "1.7.3", default-features = false, features = ["std"] }

# Actix-web
actix-web = { version = "4.3.1", default-features = false, optional = true }

# Axum
axum = { version = "0.6.12", features = ["json", "headers"], default-features = false, optional = true }
tower = { version = "0.4.13", optional = true }
hyper = { version = "0.14", optional = true }
displaydoc = "0.2.3"

[features]
default = ["actix-web", "axum"]
actix-web = ["dep:actix-web"]
axum = ["dep:axum", "dep:tower", "dep:hyper"]

[dev-dependencies]
rand = "0.8.5"
env_logger = "0.10.0"
tower-http = { version = "0.4.0", features = ["map-request-body", "util"] }
axum = { version = "0.6.12", features = ["http1", "tokio", "query"], default-features = false }
axum-macros = "0.3.7"
actix-rt = "2.8.0"

[profile.dev]
strip = "symbols"
debug = 0
