[package]
name = "tinyboards_server"
version = "0.1.0"
edition = "2021"
description = "The backend server for TinyBoards!"
license  = "AGPL-3.0"

[lib]
doctest = false

[profile.dev]
debug = 0

[features]
console = ["console-subscriber", "opentelemetry", "opentelemetry-otlp", "tracing-opentelemetry",
    "reqwest-tracing/opentelemetry_0_16"]

[workspace]
members = [
    "crates/api",
    "crates/api_common",
    "crates/api_crud",
    "crates/utils",
    "crates/db",
    "crates/db_views"
]

[dependencies]
tinyboards_api = { version = "0.1.0", path="./crates/api" }
tinyboards_api_common = { version = "0.1.0", path="./crates/api_common" }
tinyboards_api_crud = { version = "0.1.0", path="./crates/api_crud" }
tinyboards_utils = { version = "0.1.0", path="./crates/utils" }
tinyboards_db = { version = "0.1.0", path="./crates/db" }
tinyboards_db_views = { version = "0.1.0", path="./crates/db_views" }
diesel = "2.0.0"
diesel_migrations = "2.0.0"
actix = "0.13.0"
actix-web = { version = "4.2.1", default-features = false, features = ["macros", "rustls"] }
serde = { version = "1.0.145", features = ["derive"] }
bigdecimal = "0.3.0"
dotenv = "0.15.0"
tracing = "0.1.36"
tracing-actix-web = { version = "0.6.1", default-features = false }
tracing-log = "0.1.3"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
url = { version = "2.3.1", features = ["serde"] }
reqwest = { version = "0.11.12", features = ["json"] }
reqwest-middleware = "0.1.6"
reqwest-tracing = "0.3.1"
clokwerk = "0.3.5"
doku = { version = "0.12.0", features = ["url-2"] }
parking_lot = "0.12.1"
reqwest-retry = "0.1.5"
console-subscriber = { version = "0.1.8", optional = true }
opentelemetry = { version = "0.18.0", features = ["rt-tokio"], optional = true }
opentelemetry-otlp = { version = "0.11.0", optional = true }
tracing-opentelemetry = { version = "0.18.0", optional = true }