use crate::enums::*;
use crate::schema::site;
use chrono::{DateTime, Utc};
use diesel::prelude::*;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// The main site configuration row. There is exactly one row in this table.
#[derive(Debug, Clone, Serialize, Deserialize, Queryable, Identifiable)]
#[diesel(table_name = site)]
pub struct Site {
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub icon: Option<String>,
    pub homepage_banner: Option<String>,
    pub primary_color: String,
    pub secondary_color: String,
    pub hover_color: String,
    pub welcome_message: Option<String>,
    pub legal_information: Option<String>,
    pub default_theme: String,
    pub default_post_listing_type: DbListingType,
    pub default_avatar: Option<String>,
    pub registration_mode: DbRegistrationMode,
    pub application_question: Option<String>,
    pub is_site_setup: bool,
    pub is_private: bool,
    pub require_email_verification: bool,
    pub application_email_admins: bool,
    pub captcha_enabled: bool,
    pub captcha_difficulty: String,
    pub enable_downvotes: bool,
    pub enable_nsfw: bool,
    pub enable_nsfw_tagging: bool,
    pub hide_modlog_mod_names: bool,
    pub reports_email_admins: bool,
    pub boards_enabled: bool,
    pub board_creation_admin_only: bool,
    pub board_creation_mode: String,
    pub trusted_user_min_reputation: i32,
    pub trusted_user_min_account_age_days: i32,
    pub trusted_user_manual_approval: bool,
    pub trusted_user_min_posts: i32,
    pub allowed_post_types: Option<String>,
    pub word_filter_enabled: bool,
    pub filtered_words: Option<String>,
    pub word_filter_applies_to_posts: bool,
    pub word_filter_applies_to_comments: bool,
    pub word_filter_applies_to_usernames: bool,
    pub link_filter_enabled: bool,
    pub banned_domains: Option<String>,
    pub approved_image_hosts: Option<String>,
    pub image_embed_hosts_only: bool,
    pub emoji_enabled: bool,
    pub max_emojis_per_post: Option<i32>,
    pub max_emojis_per_comment: Option<i32>,
    pub emoji_max_file_size_mb: i32,
    pub board_emojis_enabled: bool,
    pub image_max_width: i32,
    pub image_max_height: i32,
    pub image_thumbnail_width: i32,
    pub image_convert_to_webp: bool,
    pub image_strip_exif: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub custom_css: Option<String>,
    pub custom_css_enabled: bool,
}

/// Form for inserting a new site row.
#[derive(Debug, Clone, Insertable)]
#[diesel(table_name = site)]
pub struct SiteInsertForm {
    pub name: String,
    pub description: Option<String>,
    pub icon: Option<String>,
    pub homepage_banner: Option<String>,
    pub primary_color: String,
    pub secondary_color: String,
    pub hover_color: String,
    pub welcome_message: Option<String>,
    pub legal_information: Option<String>,
    pub default_theme: String,
    pub default_post_listing_type: DbListingType,
    pub default_avatar: Option<String>,
    pub registration_mode: DbRegistrationMode,
    pub application_question: Option<String>,
    pub is_site_setup: bool,
    pub is_private: bool,
    pub require_email_verification: bool,
    pub application_email_admins: bool,
    pub captcha_enabled: bool,
    pub captcha_difficulty: String,
    pub enable_downvotes: bool,
    pub enable_nsfw: bool,
    pub enable_nsfw_tagging: bool,
    pub hide_modlog_mod_names: bool,
    pub reports_email_admins: bool,
    pub boards_enabled: bool,
    pub board_creation_admin_only: bool,
    pub board_creation_mode: String,
    pub trusted_user_min_reputation: i32,
    pub trusted_user_min_account_age_days: i32,
    pub trusted_user_manual_approval: bool,
    pub trusted_user_min_posts: i32,
    pub allowed_post_types: Option<String>,
    pub word_filter_enabled: bool,
    pub filtered_words: Option<String>,
    pub word_filter_applies_to_posts: bool,
    pub word_filter_applies_to_comments: bool,
    pub word_filter_applies_to_usernames: bool,
    pub link_filter_enabled: bool,
    pub banned_domains: Option<String>,
    pub approved_image_hosts: Option<String>,
    pub image_embed_hosts_only: bool,
    pub emoji_enabled: bool,
    pub max_emojis_per_post: Option<i32>,
    pub max_emojis_per_comment: Option<i32>,
    pub emoji_max_file_size_mb: i32,
    pub board_emojis_enabled: bool,
    pub custom_css: Option<String>,
    pub custom_css_enabled: bool,
}

/// Form for updating an existing site row. All fields are optional so only
/// the columns that need to change are included in the UPDATE statement.
#[derive(Debug, Clone, Default, AsChangeset)]
#[diesel(table_name = site)]
pub struct SiteUpdateForm {
    pub name: Option<String>,
    pub description: Option<Option<String>>,
    pub icon: Option<Option<String>>,
    pub homepage_banner: Option<Option<String>>,
    pub primary_color: Option<String>,
    pub secondary_color: Option<String>,
    pub hover_color: Option<String>,
    pub welcome_message: Option<Option<String>>,
    pub legal_information: Option<Option<String>>,
    pub default_theme: Option<String>,
    pub default_post_listing_type: Option<DbListingType>,
    pub default_avatar: Option<Option<String>>,
    pub registration_mode: Option<DbRegistrationMode>,
    pub application_question: Option<Option<String>>,
    pub is_site_setup: Option<bool>,
    pub is_private: Option<bool>,
    pub require_email_verification: Option<bool>,
    pub application_email_admins: Option<bool>,
    pub captcha_enabled: Option<bool>,
    pub captcha_difficulty: Option<String>,
    pub enable_downvotes: Option<bool>,
    pub enable_nsfw: Option<bool>,
    pub enable_nsfw_tagging: Option<bool>,
    pub hide_modlog_mod_names: Option<bool>,
    pub reports_email_admins: Option<bool>,
    pub boards_enabled: Option<bool>,
    pub board_creation_admin_only: Option<bool>,
    pub board_creation_mode: Option<String>,
    pub trusted_user_min_reputation: Option<i32>,
    pub trusted_user_min_account_age_days: Option<i32>,
    pub trusted_user_manual_approval: Option<bool>,
    pub trusted_user_min_posts: Option<i32>,
    pub allowed_post_types: Option<Option<String>>,
    pub word_filter_enabled: Option<bool>,
    pub filtered_words: Option<Option<String>>,
    pub word_filter_applies_to_posts: Option<bool>,
    pub word_filter_applies_to_comments: Option<bool>,
    pub word_filter_applies_to_usernames: Option<bool>,
    pub link_filter_enabled: Option<bool>,
    pub banned_domains: Option<Option<String>>,
    pub approved_image_hosts: Option<Option<String>>,
    pub image_embed_hosts_only: Option<bool>,
    pub emoji_enabled: Option<bool>,
    pub max_emojis_per_post: Option<Option<i32>>,
    pub max_emojis_per_comment: Option<Option<i32>>,
    pub emoji_max_file_size_mb: Option<i32>,
    pub board_emojis_enabled: Option<bool>,
    pub custom_css: Option<Option<String>>,
    pub custom_css_enabled: Option<bool>,
}
