CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    passhash VARCHAR(255) NOT NULL,
    created_utc INT NOT NULL,
    admin_level SMALLINT NOT NULL,
    is_activated BOOLEAN NOT NULL DEFAULT false,
    over_18 BOOLEAN NOT NULL DEFAULT false,
    creation_ip VARCHAR(15) NOT NULL DEFAULT '',
    bio VARCHAR(1000) DEFAULT '',
    bio_html VARCHAR(1000) DEFAULT '',
    referred_by INT DEFAULT NULL,
    is_banned BOOLEAN DEFAULT false,
    unban_utc INT DEFAULT 0,
    ban_reason VARCHAR(255) DEFAULT '',
    defaultsorting VARCHAR(10) DEFAULT 'hot',
    defaulttime VARCHAR(10) DEFAULT 'all',
    feed_nonce INT DEFAULT 0,
    login_nonce INT DEFAULT 0,
    has_profile BOOLEAN DEFAULT false,
    has_banner BOOLEAN DEFAULT false,
    reserved VARCHAR(256) DEFAULT NULL,
    is_nsfw BOOLEAN DEFAULT false,
    tos_agreed_utc INT DEFAULT 0,
    profile_nonce INT DEFAULT 0,
    banner_nonce INT DEFAULT 0,
    mfa_secret VARCHAR(16) DEFAULT NULL,
    hide_offensive BOOLEAN DEFAULT false,
    hide_bot BOOLEAN DEFAULT false,
    show_nsfl BOOLEAN DEFAULT false,
    is_private BOOLEAN DEFAULT false,
    is_deleted BOOLEAN DEFAULT false,
    delete_reason VARCHAR(500) DEFAULT '',
    filter_nsfw BOOLEAN DEFAULT false,
    stored_karma INT DEFAULT 0,
    stored_subscriber_count INT DEFAULT 0,
    auto_join_chat BOOLEAN DEFAULT false,
    is_nofollow BOOLEAN DEFAULT false,
    custom_filter_list VARCHAR(1000) DEFAULT '',
    discord_id VARCHAR(64) DEFAULT NULL,
    creation_region VARCHAR(2) DEFAULT NULL,
    ban_evade INT DEFAULT 0,
    profile_upload_ip VARCHAR(15) DEFAULT '',
    banner_upload_ip VARCHAR(15) DEFAULT '',
    profile_upload_region VARCHAR(2) DEFAULT '',
    banner_upload_region VARCHAR(2) DEFAULT '',
    color VARCHAR(6) DEFAULT '805ad5',
    secondary_color VARCHAR(6) DEFAULT 'ffff00',
    comment_signature VARCHAR(280) DEFAULT '',
    comment_signature_html VARCHAR(512) DEFAULT '',
    profile_set_utc INT DEFAULT 0,
    bannner_set_utc INT DEFAULT 0,
    original_username VARCHAR(255) DEFAULT '',
    name_changed_utc INT DEFAULT 0
)