version: '3.8'

# Development-optimized Docker Compose configuration
# Features: hot reloading, debugging support, optimized caching

# Common logging configuration for development
x-logging: &dev-logging
  logging:
    driver: "json-file"
    options:
      max-size: "50m"
      max-file: "5"
      labels: "service,environment=development"

# Common restart policy for development
x-restart-policy: &dev-restart
  restart: "no"  # Don't auto-restart in dev to see crashes

services:
  # Nginx reverse proxy for development
  nginx:
    image: nginx:1.25-alpine
    container_name: tinyboards_nginx_dev
    ports:
      - "80:80"
      - "8080:8080"  # Alternative port for testing
    volumes:
      - ./nginx/conf/dev/:/etc/nginx/conf.d:ro
      - nginx_cache_dev:/var/cache/nginx
      # Mount logs for debugging
      - ./logs/nginx:/var/log/nginx
    networks:
      - tinyboards_dev
    <<: *dev-restart
    <<: *dev-logging
    depends_on:
      tinyboards:
        condition: service_started
      tinyboards-fe:
        condition: service_started
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d

  # TinyBoards backend with development optimizations
  tinyboards:
    image: tinyboards:dev
    container_name: tinyboards_backend_dev
    ports:
      - "8536:8536"  # Main API port
      - "6669:6669"  # WebSocket port
      - "9229:9229"  # Debug port for potential future use
    <<: *dev-restart
    <<: *dev-logging
    environment:
      - RUST_LOG=debug,tinyboards_api=trace,tinyboards_db=debug
      - RUST_BACKTRACE=full
      - DATABASE_URL=postgresql://tinyboards:tinyboards@postgres:5432/tinyboards
      - TB_CONFIG_LOCATION=/config/defaults.hjson
      - ENVIRONMENT=development
      # Development-specific settings
      - CARGO_INCREMENTAL=1
      - RUST_LOG_STYLE=always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: runtime  # Use optimized multi-stage build
      cache_from:
        - tinyboards:dev
        - rust:1.75-slim-bookworm
    volumes:
      # Configuration
      - ./tinyboards.hjson:/config/defaults.hjson:ro
      # Media uploads with proper permissions
      - media_uploads_dev:/app/media
      # Source code for development (if using dev build)
      - ../src:/app/src:ro
      - ../crates:/app/crates:ro
      - ../Cargo.toml:/app/Cargo.toml:ro
      - ../Cargo.lock:/app/Cargo.lock:ro
      # Cargo cache for faster rebuilds
      - cargo_cache_dev:/usr/local/cargo
      - cargo_target_dev:/app/target
      # Logs
      - ./logs/backend:/app/logs
    networks:
      - tinyboards_dev
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8536/api/v1/site || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    # Resource limits for development
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '1.0'

  # TinyBoards frontend with hot reloading
  tinyboards-fe:
    image: tinyboards-fe:dev
    container_name: tinyboards_frontend_dev
    ports:
      - "3000:3000"  # Main frontend port
      - "24678:24678"  # Nuxt DevTools port
    <<: *dev-restart
    <<: *dev-logging
    environment:
      - NODE_ENV=development
      - NITRO_PORT=3000
      - NITRO_HOST=0.0.0.0
      - NUXT_DEVTOOLS_ENABLED=true
      - NUXT_PUBLIC_API_BASE=http://localhost:8536
    build:
      context: ../../tinyboards-fe
      dockerfile: Dockerfile.dev  # Assume we'll create this
      cache_from:
        - tinyboards-fe:dev
        - node:18-alpine
    volumes:
      # Source code for hot reloading
      - ../../tinyboards-fe:/usr/src/app
      - /usr/src/app/node_modules  # Anonymous volume for node_modules
      # Configuration
      - ./.env:/usr/src/app/.env:ro
      # Logs
      - ./logs/frontend:/usr/src/app/logs
      # NPM cache for faster installs
      - npm_cache_dev:/home/node/.npm
    networks:
      - tinyboards_dev
    depends_on:
      tinyboards:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Resource limits for development
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

  # PostgreSQL with development optimizations
  postgres:
    image: postgres:15-alpine
    container_name: tinyboards_postgres_dev
    ports:
      - "5433:5432"  # Use different port to avoid conflicts
    environment:
      - POSTGRES_USER=tinyboards
      - POSTGRES_PASSWORD=tinyboards
      - POSTGRES_DB=tinyboards
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=C --lc-ctype=C
      # Development-specific settings
      - POSTGRES_HOST_AUTH_METHOD=trust  # Only for development!
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
      - ./postgres/dev-config:/etc/postgresql:ro
      # Logs for debugging
      - ./logs/postgres:/var/log/postgresql
    networks:
      - tinyboards_dev
    <<: *dev-restart
    <<: *dev-logging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tinyboards -d tinyboards"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # Development-optimized PostgreSQL configuration
    command: [
      "postgres",
      # Development-specific settings for faster queries and debugging
      "-c", "log_statement=all",
      "-c", "log_min_duration_statement=0",
      "-c", "log_line_prefix=%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h ",
      "-c", "log_checkpoints=on",
      "-c", "log_connections=on",
      "-c", "log_disconnections=on",
      "-c", "log_lock_waits=on",
      "-c", "log_temp_files=0",
      # Performance settings for development
      "-c", "shared_buffers=256MB",
      "-c", "effective_cache_size=1GB",
      "-c", "work_mem=16MB",
      "-c", "maintenance_work_mem=256MB",
      "-c", "checkpoint_completion_target=0.9",
      "-c", "wal_buffers=16MB",
      "-c", "default_statistics_target=100",
      # Development debugging
      "-c", "session_preload_libraries=auto_explain",
      "-c", "auto_explain.log_min_duration=100ms",
      "-c", "auto_explain.log_analyze=true",
      "-c", "auto_explain.log_buffers=true",
      "-c", "auto_explain.log_timing=true",
      "-c", "auto_explain.log_triggers=true",
      "-c", "auto_explain.log_verbose=true"
    ]
    # Resource limits for development
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Redis for caching and sessions (development)
  redis:
    image: redis:7-alpine
    container_name: tinyboards_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
      - ./redis/dev-config:/usr/local/etc/redis:ro
    networks:
      - tinyboards_dev
    <<: *dev-restart
    <<: *dev-logging
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--maxmemory", "256mb",
      "--maxmemory-policy", "allkeys-lru",
      "--save", "60", "1",  # More frequent saves in development
      "--loglevel", "verbose"  # More verbose logging for development
    ]

  # Development tools and utilities
  adminer:
    image: adminer:4.8.1
    container_name: tinyboards_adminer_dev
    ports:
      - "8081:8080"
    networks:
      - tinyboards_dev
    <<: *dev-restart
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=hydra
    depends_on:
      postgres:
        condition: service_healthy

  # Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: tinyboards_redis_commander_dev
    ports:
      - "8082:8081"
    networks:
      - tinyboards_dev
    <<: *dev-restart
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    depends_on:
      - redis

networks:
  tinyboards_dev:
    name: tinyboards_dev_network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-tinyboards-dev
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
          ip_range: 172.21.240.0/20

volumes:
  # Application data
  media_uploads_dev:
    name: tinyboards_media_dev
    driver: local
  postgres_data_dev:
    name: tinyboards_postgres_dev
    driver: local
  redis_data_dev:
    name: tinyboards_redis_dev
    driver: local

  # Build caches for faster development
  cargo_cache_dev:
    name: tinyboards_cargo_cache_dev
    driver: local
  cargo_target_dev:
    name: tinyboards_cargo_target_dev
    driver: local
  npm_cache_dev:
    name: tinyboards_npm_cache_dev
    driver: local
  nginx_cache_dev:
    name: tinyboards_nginx_cache_dev
    driver: local