version: '3.3'

services:
  nginx:
    image: nginx:1-alpine
    ports:
      - "1236:1236"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      tinyboards:
        aliases:
          - nginx
    restart: always

  tinyboards:
    image: tinyboards-dev
    ports:
      - "8536:8536"
      - "6669:6669"
    restart: always
    environment:
      - RUST_LOG="info"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    links:
      - postgres
    networks:
      tinyboards:
        aliases:
          - tinyboards-be

    # might need to add a volume bridge here for a custom config file, otherwise the dockerfile sets up the default config

  tinyboards-fe:
    image: tinyboards-fe-dev
    ports:
      - "3000:3000"
    restart: always
    build:
      context: ../../tinyboards-fe
      dockerfile: Dockerfile
    volumes:
      - ../../tinyboards-fe/package.json:/usr/src/app/package.json
      - ../../tinyboards-fe/package.json:/usr/src/app/package-lock.json
    networks:
      tinyboards:
        aliases:
          - tinyboards-fe
    depends_on:
      - tinyboards


  postgres:
    image: postgres:14-alpine
    ports:
      # use a different port so it doesn't conflict with postgres running on the host
      - "5433:5432"
    environment:
      - POSTGRES_USER=tinyboards
      - POSTGRES_PASSWORD=tinyboards
      - POSTGRES_DB=tinyboards
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      tinyboards:
        aliases:
          - postgres
    restart: always
    command: ["postgres", "-c", "session_preload_libraries=auto_explain", "-c", "auto_explain.log_min_duration=5ms", "-c", "auto_explain.log_analyze=true"]
networks:
  tinyboards: {}