use diesel::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Queryable, Serialize, Deserialize)]
pub struct Boards {
    id: i32,
    board_name: String,
    created_utc: i32,
    board_description: Option<String>,
    board_description_html: Option<String>,
    over_18: bool,
    is_nsfl: bool,
    is_banned: bool,
    has_banner: bool,
    has_profile: bool,
    creator_id: i32,
    ban_reason: Option<String>,
    color: String,
    restricted_posting: bool,
    disallowbots: bool,
    hide_banner_data: bool,
    profile_nonce: i32,
    banner_nonce: i32,
    is_private: bool,
    color_nonce: i32,
    rank_trending: f64,
    stored_subscriber_count: i32,
    all_opt_out: bool,
    is_locked_category: bool,
    subcat_id: i32,
    secondary_color: String,
    public_chat: bool,
    motd: String,
    css_nonce: i32,
    css: String,
}
