use diesel::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Queryable, Serialize, Deserialize)]
pub struct Comments {
    id: i32,
    body: Option<String>,
    body_html: Option<String>,
    ban_reason: String,
    author_id: i32,
    parent_submission: i32,
    created_utc: i32,
    edited_utc: i32,
    is_banned: bool,
    gm_distinguish: i32,
    distinguished_board: i32,
    deleted_utc: i32,
    purged_utc: i32,
    is_approved: i32,
    approved_utc: i32,
    creation_ip: String,
    score_disputed: f64,
    score_hot: f64,
    score_top: f64,
    comment_level: i32,
    parent_comment_id: i32,
    original_board_id: i32,
    over_18: bool,
    is_offensive: bool,
    is_nsfl: bool,
    is_bot: bool,
    is_pinned: bool,
    creation_region: Option<String>,
    app_id: Option<i32>,
    upvotes: i32,
    downvotes: i32,
}
