[package]
name = "porpl-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = { version = "1.0.145", features = ["derive"] }
derive_more = "0.99.17"
rust-argon2 = "1.0"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
