[package]
name = "porpl_utils"
version = "0.1.0"
edition = "2021"

[lib]
name = "porpl_utils"
path = "src/lib.rs"
doctest = false

[dependencies]
actix-web = "4"
serde = { version = "1.0.145", features = ["derive"] }
derive_more = "0.99.17"
rust-argon2 = "1.0"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
chrono = "0.4.22"
temp-env = "0.3.0"

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",
    "fast-rng",
    "macro-diagnostics"
]

