DROP TABLE IF EXISTS submissions;
DROP TABLE IF EXISTS subcategories;
DROP TABLE IF EXISTS boards;
DROP TABLE IF EXISTS domains;
DROP TABLE IF EXISTS badlinks;
DROP TABLE IF EXISTS oauth_apps;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS mods;
