[package]
name = "porpl-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.0", features = ["postgres", "r2d2", "64-column-tables"] }
r2d2 = "0.8.10"
dotenvy = "0.15"
serde = { version = "1.0.145", features = ["derive"] }
bigdecimal = "0.3.0"
