drop view mod_remove_post_view;
drop view mod_lock_post_view;
drop view mod_remove_comment_view;
drop view mod_remove_board_view;
drop view mod_ban_from_board_view;
drop view mod_ban_view;
drop view mod_add_board_view;
drop view mod_add_view;
drop view mod_sticky_post_view;