use crate::{newtypes::DbUrl, schema::boards};
use chrono::NaiveDateTime;
use diesel::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, PartialEq, Eq, Debug, Serialize, Deserialize, Queryable, Identifiable)]
#[diesel(table_name = boards)]
pub struct Board {
    pub id: i32,
    pub name: String,
    pub title: String,
    pub description: Option<String>,
    pub creation_date: NaiveDateTime,
    pub updated: Option<NaiveDateTime>,
    pub is_deleted: bool,
    pub is_nsfw: bool,
    pub is_hidden: bool,
    pub last_refreshed_date: NaiveDateTime,
    pub instance_id: i32,
    pub icon: Option<DbUrl>,
    pub banner: Option<DbUrl>,
    pub posting_restricted_to_mods: bool,
    pub is_removed: bool,
    pub ban_reason: Option<String>,
    pub primary_color: String,
    pub secondary_color: String,
    pub hover_color: String,
    pub sidebar: Option<String>,
    pub sidebar_html: Option<String>,
    pub is_banned: bool,
    pub public_ban_reason: Option<String>,
    pub banned_by: Option<i32>,
    pub banned_at: Option<NaiveDateTime>,
    pub exclude_from_all: bool,
    pub moderators_url: Option<String>,
    pub featured_url: Option<String>,
    pub section_config: i32,
    pub section_order: Option<String>,
    pub default_section: Option<String>,
}

#[derive(Clone, PartialEq, Eq, Debug, Serialize, Deserialize, Default, Insertable, AsChangeset)]
#[diesel(table_name = boards)]
pub struct BoardForm {
    pub name: Option<String>,
    pub title: Option<String>,
    pub description: Option<Option<String>>,
    pub updated: Option<Option<NaiveDateTime>>,
    pub is_deleted: Option<bool>,
    pub is_nsfw: Option<bool>,
    pub is_hidden: Option<bool>,
    pub last_refreshed_date: Option<NaiveDateTime>,
    pub instance_id: Option<i32>,
    pub icon: Option<DbUrl>,
    pub banner: Option<DbUrl>,
    pub posting_restricted_to_mods: Option<bool>,
    pub is_removed: Option<bool>,
    pub ban_reason: Option<Option<String>>,
    pub primary_color: Option<String>,
    pub secondary_color: Option<String>,
    pub hover_color: Option<String>,
    pub sidebar: Option<Option<String>>,
    pub sidebar_html: Option<Option<String>>,
    pub is_banned: Option<bool>,
    pub public_ban_reason: Option<Option<String>>,
    pub banned_by: Option<Option<i32>>,
    pub banned_at: Option<Option<NaiveDateTime>>,
    pub exclude_from_all: Option<bool>,
    pub moderators_url: Option<Option<String>>,
    pub featured_url: Option<Option<String>>,
    pub section_config: Option<i32>,
    pub section_order: Option<Option<String>>,
    pub default_section: Option<Option<String>>,
}

/// A safe representation of board, without the sensitive info
#[derive(Clone, PartialEq, Eq, Debug, Serialize, Deserialize, Queryable, Identifiable)]
#[diesel(table_name = boards)]
pub struct BoardSafe {
    pub id: i32,
    pub name: String,
    pub title: String,
    pub icon: Option<DbUrl>,
    pub banner: Option<DbUrl>,
    pub description: Option<String>,
    pub creation_date: chrono::NaiveDateTime,
    pub updated: Option<NaiveDateTime>,
    pub is_deleted: bool,
    pub is_removed: bool,
    pub is_nsfw: bool,
    pub is_hidden: bool,
    pub ban_reason: Option<String>,
    pub primary_color: String,
    pub secondary_color: String,
    pub hover_color: String,
    pub sidebar: Option<String>,
    pub sidebar_html: Option<String>,
    pub is_banned: bool,
    pub public_ban_reason: Option<String>,
    pub banned_by: Option<i32>,
    pub banned_at: Option<NaiveDateTime>,
    pub exclude_from_all: bool,
    pub moderators_url: Option<String>,
    pub featured_url: Option<String>,
    pub section_config: i32,
    pub section_order: Option<String>,
    pub default_section: Option<String>,
}
