-- Reverse foundation: drop functions, enums, extensions

DROP FUNCTION IF EXISTS current_app_user_id() CASCADE;
DROP FUNCTION IF EXISTS controversy_rank(NUMERIC, NUMERIC) CASCADE;
DROP FUNCTION IF EXISTS hot_rank(NUMERIC, TIMESTAMPTZ) CASCADE;
DROP FUNCTION IF EXISTS add_updated_at_trigger(TEXT) CASCADE;
DROP FUNCTION IF EXISTS set_updated_at() CASCADE;

DROP TYPE IF EXISTS report_status CASCADE;
DROP TYPE IF EXISTS emoji_scope CASCADE;
DROP TYPE IF EXISTS filter_mode CASCADE;
DROP TYPE IF EXISTS flair_type CASCADE;
DROP TYPE IF EXISTS wiki_permission CASCADE;
DROP TYPE IF EXISTS moderation_action CASCADE;
DROP TYPE IF EXISTS notification_kind CASCADE;
DROP TYPE IF EXISTS editor_mode CASCADE;
DROP TYPE IF EXISTS approval_status CASCADE;
DROP TYPE IF EXISTS listing_type CASCADE;
DROP TYPE IF EXISTS sort_type CASCADE;
DROP TYPE IF EXISTS post_type CASCADE;
DROP TYPE IF EXISTS registration_mode CASCADE;

DROP EXTENSION IF EXISTS "pg_trgm";
DROP EXTENSION IF EXISTS "pgcrypto";
